version: '3.7'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        platform: linux/arm64/v8
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /home/ubuntu/moabam/nginx/certbot/conf:/etc/letsencrypt
            - /home/ubuntu/moabam/nginx/certbot/www:/var/www/certbot
            - /home/ubuntu/moabam/nginx/nginx.conf:/etc/nginx/nginx.conf
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot:latest
        container_name: certbot
        platform: linux/arm64
        restart: unless-stopped
        volumes:
            - /home/ubuntu/moabam/nginx/certbot/conf:/etc/letsencrypt
            - /home/ubuntu/moabam/nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    moabam-blue:
        image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPOSITORY}:${DOCKER_HUB_TAG}
        container_name: ${BLUE_CONTAINER}
        restart: always
        expose:
            - ${SERVER_PORT}
        depends_on:
            - redis
            - mysql
        environment:
            SPRING_ACTIVE_PROFILES: ${SPRING_ACTIVE_PROFILES}
    moabam-green:
        image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPOSITORY}:${DOCKER_HUB_TAG}
        container_name: ${GREEN_CONTAINER}
        expose:
            - ${SERVER_PORT}
        depends_on:
            - redis
            - mysql
        environment:
            SPRING_ACTIVE_PROFILES: ${SPRING_ACTIVE_PROFILES}
    redis:
        image: redis:alpine
        container_name: redis
        platform: linux/arm64
        restart: always
        command: redis-server
        ports:
            - "6379:6379"
        volumes:
            - /home/ubuntu/moabam/data/redis:/data
    mysql:
        image: mysql:8.0.33
        container_name: mysql
        platform: linux/arm64/v8
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DEV_MYSQL_DATABASE}
            MYSQL_USERNAME: ${DEV_MYSQL_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DEV_MYSQL_PASSWORD}
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - /home/ubuntu/moabam/data/mysql:/var/lib/mysql
